import{useEffect,useState}from"react";import{useNavigate,useParams}from"react-router-dom";import Layout from"../components/Layout";import AssetForm from"../components/assets/AssetForm";import{useToast}from"../design-system";import assetService from"../services/assetService";import{useTranslation}from"../i18n/LanguageContext";import"../components/assets/assets.css";
const empty={itemNumber:"Auto-generated",serialNumber:"",deviceType:"laptop",customDeviceType:"",brand:"",model:"",productYear:"",generation:"",assetValue:"",supplier:"",invoiceImage:"",hasWarranty:true,warrantyStartDate:"",warrantyEndDate:"",notes:""};
function AddAsset(){const{id}=useParams();const isEditing=Boolean(id);const navigate=useNavigate();const{enumLabel,t}=useTranslation();const{toast}=useToast();const[form,setForm]=useState(empty);const[error,setError]=useState("");const[loading,setLoading]=useState(isEditing);
  useEffect(()=>{if(!isEditing)return;let active=true;assetService.get(id).then((asset)=>{if(active)setForm(fromAsset(asset));}).catch((err)=>{if(active)setError(err.response?.data?.message||"Could not load this asset");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id,isEditing]);
  const invoice=(event)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>5*1024*1024){setError(t("ui.selectInvoiceImage"));return;}const reader=new FileReader();reader.onload=()=>setForm((current)=>({...current,invoiceImage:reader.result}));reader.readAsDataURL(file);};
  const submit=async(event)=>{event.preventDefault();setLoading(true);setError("");try{const payload=isEditing?form:{...form,itemNumber:undefined,assetId:undefined};if(isEditing)await assetService.update(id,payload);else await assetService.create(payload);toast(isEditing?t("assetPage.assetRecordUpdated"):t("assetPage.assetRecordUpdated"),{tone:"success"});navigate("/assets");}catch(err){setError(err.response?.data?.message||t("assets.createError"));}finally{setLoading(false);}};
  return <Layout><main className="enterprise-assets"><header className="asset-page-header"><div><p className="asset-kicker">{t("assetPage.assetManagement")}</p><h1>{isEditing?t("assetPage.saveChanges"):t("assetPage.addAsset")}</h1><p>{isEditing?t("assetPage.saveChanges"):t("assetPage.trackDevices")}</p></div></header><AssetForm form={form} setForm={setForm} isEditing={isEditing} loading={loading} error={error} enumLabel={enumLabel} onInvoice={invoice} onSubmit={submit} onCancel={()=>navigate("/assets")}/></main></Layout>;
}
function fromAsset(asset){return{itemNumber:asset.itemNumber||asset.assetId||"",serialNumber:asset.serialNumber||"",deviceType:asset.deviceType||"laptop",customDeviceType:asset.customDeviceType||"",brand:asset.brand||"",model:asset.model||"",productYear:asset.productYear||"",generation:asset.generation||"",assetValue:asset.assetValue??"",supplier:asset.supplier||"",invoiceImage:asset.invoiceImage||"",hasWarranty:asset.hasWarranty!==false,warrantyStartDate:asset.warrantyStartDate?.slice(0,10)||"",warrantyEndDate:(asset.warrantyEndDate||asset.warrantyDate)?.slice(0,10)||"",notes:asset.notes||""};}
export default AddAsset;
