import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import Layout from"../components/Layout";import CustodyDetails from"../components/asset-custody/CustodyDetails";import CustodyFilters from"../components/asset-custody/CustodyFilters";import CustodyHeader from"../components/asset-custody/CustodyHeader";import CustodyTable from"../components/asset-custody/CustodyTable";import IssueAssetDialog from"../components/asset-custody/IssueAssetDialog";import ReturnAssetDialog from"../components/asset-custody/ReturnAssetDialog";import TransferAssetDialog from"../components/asset-custody/TransferAssetDialog";import{assetLabel}from"../components/asset-custody/custodyUtils";import{ConfirmationDialog,ErrorState,Textarea,useToast}from"../design-system";import assetService from"../services/assetService";import{useTranslation}from"../i18n/LanguageContext";import"../components/asset-custody/custody.css";
function AssetIssues(){const navigate=useNavigate();const{formatDate,formatDateTime}=useTranslation();const{toast}=useToast();const[issues,setIssues]=useState([]);const[users,setUsers]=useState([]);const[assets,setAssets]=useState([]);const[filters,setFilters]=useState({search:"",status:""});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[issueOpen,setIssueOpen]=useState(false);const[selected,setSelected]=useState(null);const[returnTarget,setReturnTarget]=useState(null);const[transferTarget,setTransferTarget]=useState(null);const[destroyTarget,setDestroyTarget]=useState(null);const[reason,setReason]=useState("");
  const load=async()=>{const[records,people,items]=await Promise.all([assetService.listCustody(),assetService.listUsers(),assetService.list()]);setIssues(records);setUsers(people);setAssets(items);};
  useEffect(()=>{let active=true;Promise.all([assetService.listCustody(),assetService.listUsers(),assetService.list()]).then(([records,people,items])=>{if(active){setIssues(records);setUsers(people);setAssets(items);}}).catch((err)=>{if(active)setError(err.response?.data?.message||"Could not load custody records");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const filtered=useMemo(()=>issues.filter((issue)=>{const term=filters.search.trim().toLowerCase();const searchable=[issue.item?.itemNumber,issue.item?.assetId,issue.item?.serialNumber,issue.item?.brand,issue.item?.model,issue.user?.name,issue.userSnapshot?.name,issue.user?.employeeId,issue.issuedBy?.name,issue.returnedBy?.name,issue.transferredBy?.name].filter(Boolean).join(" ").toLowerCase();return(!term||searchable.includes(term))&&(!filters.status||issue.status===filters.status);}),[filters,issues]);
  const execute=async(action,message,close)=>{setSaving(true);setError("");try{await action();await load();toast(message,{tone:"success"});close?.();return true;}catch(err){setError(err.response?.data?.message||"Custody action could not be completed");return false;}finally{setSaving(false);}};
  const issueAsset=(payload)=>execute(()=>assetService.issue(payload),"Asset issued successfully",()=>setIssueOpen(false));const returnAsset=()=>execute(()=>assetService.returnCustody(returnTarget._id),"Asset returned successfully",()=>setReturnTarget(null));const transferAsset=(payload)=>execute(()=>assetService.transfer(transferTarget._id,payload),"Asset transferred successfully",()=>setTransferTarget(null));const destroyAsset=()=>execute(()=>assetService.destroyCustody(destroyTarget._id,reason.trim()),"Asset destroyed and removed from custody",()=>{setDestroyTarget(null);setReason("");});
  return <Layout><main className="enterprise-custody"><CustodyHeader onIssue={()=>setIssueOpen(true)} onAssets={()=>navigate("/assets")}/>{error&&<ErrorState title="Custody records unavailable" message={error}/>}<CustodyFilters filters={filters} onChange={setFilters}/><CustodyTable issues={filtered} loading={loading} formatDate={formatDate} onView={setSelected} onReturn={setReturnTarget} onTransfer={setTransferTarget} onDestroy={setDestroyTarget}/><IssueAssetDialog open={issueOpen} onClose={()=>setIssueOpen(false)} users={users} assets={assets} issues={issues} loading={saving} onSubmit={issueAsset}/><ReturnAssetDialog issue={returnTarget} onClose={()=>setReturnTarget(null)} onConfirm={returnAsset} loading={saving}/><TransferAssetDialog issue={transferTarget} users={users} onClose={()=>setTransferTarget(null)} onSubmit={transferAsset} loading={saving}/><CustodyDetails issue={selected} open={Boolean(selected)} onClose={()=>setSelected(null)} formatDate={formatDate} formatDateTime={formatDateTime}/><ConfirmationDialog open={Boolean(destroyTarget)} onClose={()=>{setDestroyTarget(null);setReason("");}} onConfirm={destroyAsset} danger loading={saving} title="Destroy issued asset" message={<div className="custody-confirm"><p>Destroy {destroyTarget?assetLabel(destroyTarget.item):"this asset"} and remove it from the responsible employee?</p><Textarea label="Reason or reference" required value={reason} onChange={(event)=>setReason(event.target.value)}/></div>} confirmLabel="Destroy asset"/></main></Layout>;
}
export default AssetIssues;
