import { useMemo, useState } from "react";
import Layout from "../components/Layout";
import { Button, ConfirmationDialog, ErrorState, Input, Modal, Select, Textarea, useToast } from "../design-system";
import { hasRole, NETWORK_MONITORING_MANAGE_ROLES } from "../utils/roles";
import { useTranslation } from "../i18n/LanguageContext";
import useNetworkMonitoring from "../hooks/useNetworkMonitoring";
import networkService from "../services/networkService";
import NetworkHeader from "../components/network/NetworkHeader";
import NetworkSummary from "../components/network/NetworkSummary";
import NetworkFilters from "../components/network/NetworkFilters";
import DeviceTable from "../components/network/DeviceTable";
import DeviceDetails from "../components/network/DeviceDetails";
import NetworkAlerts from "../components/network/NetworkAlerts";
import "../components/network/network.css";

const TYPES=[["pc","PC"],["server","Server"],["printer","Printer"],["router","Router"],["switch","Switch"],["access_point","Access Point"],["cctv_nvr","CCTV / NVR"],["biometric","Biometric"],["other","Other"]];
const EMPTY={name:"",hostname:"",ipAddress:"",deviceType:"pc",department:"",building:"",floor:"",room:"",description:"",monitoringEnabled:true,checkMethod:"icmp",tcpPort:"",checkIntervalSeconds:"60",timeoutMs:"3000",failureThreshold:"3"};
export default function NetworkMonitoring(){const {formatDateTime}=useTranslation(); const {toast}=useToast(); const user=useMemo(()=>JSON.parse(localStorage.getItem("user")||"null"),[]); const canManage=hasRole(user,NETWORK_MONITORING_MANAGE_ROLES); const [filters,setFilters]=useState({search:"",status:"",deviceType:"",department:"",building:""}); const [form,setForm]=useState(EMPTY); const [editing,setEditing]=useState(null); const [showForm,setShowForm]=useState(false); const [confirm,setConfirm]=useState(null); const [range,setRange]=useState("24h"); const [selected,setSelected]=useState(null); const [formBusy,setFormBusy]=useState(false); const model=useNetworkMonitoring(filters); const change=(key)=>(e)=>setForm({...form,[key]:e.target.value});
 const openCreate=()=>{setEditing(null);setForm(EMPTY);setShowForm(true);}; const openEdit=(d)=>{setEditing(d);setForm({...EMPTY,...d,tcpPort:d.tcpPort??""});setShowForm(true);};
 const save=async(e)=>{e.preventDefault();setFormBusy(true);try{const p={...form,tcpPort:form.tcpPort===""?null:Number(form.tcpPort),checkIntervalSeconds:Number(form.checkIntervalSeconds),timeoutMs:Number(form.timeoutMs),failureThreshold:Number(form.failureThreshold)}; if(editing) await networkService.update(editing._id,p); else await networkService.create(p); await model.load();toast(editing?"Device updated":"Device added",{tone:"success"});setEditing(null);setShowForm(false);}catch(err){model.setError(err.response?.data?.message||"Unable to save device");}finally{setFormBusy(false);}};
 const run=(key,d,fn)=>model.action(`${key}-${d._id}`,fn).then(ok=>{if(ok)toast("Network action completed",{tone:"success"});}); const remove=()=>{if(!confirm)return;run("delete",confirm,()=>networkService.remove(confirm._id)).then(()=>setConfirm(null));};
 return <Layout><main className="enterprise-network"><NetworkHeader canManage={canManage} onAdd={openCreate}/>{model.error&&<ErrorState title="Monitoring unavailable" message={model.error}/>}<NetworkSummary summary={model.summary} formatDateTime={formatDateTime}/><NetworkAlerts incidents={model.incidents}/><NetworkFilters filters={filters} onChange={setFilters}/><DeviceTable devices={model.devices} loading={model.loading} formatDateTime={formatDateTime} onView={(d)=>{setSelected(d);model.select(d,range)}} onCheck={d=>run("check",d,()=>networkService.check(d._id))} onEdit={openEdit} onDelete={setConfirm}/><DeviceDetails device={model.selectedDevice||selected} open={Boolean(selected)} onClose={()=>{setSelected(null);model.setSelectedDevice(null)}} history={model.history} range={range} onRangeChange={r=>{setRange(r);if(selected)model.select(selected,r)}} uptimePercent={model.uptimePercent} formatDateTime={formatDateTime} loading={model.detailLoading} onCheck={d=>run("check",d,()=>networkService.check(d._id))}/>{canManage&&<Modal open={showForm} onClose={()=>setShowForm(false)} title={editing?"Edit network device":"Add network device"}><form className="network-device-form" onSubmit={save}><div className="network-form-grid"><Input label="Device name" required value={form.name} onChange={change("name")}/><Input label="Hostname" value={form.hostname} onChange={change("hostname")}/><Input label="IP address" required value={form.ipAddress} onChange={change("ipAddress")}/><Select label="Device type" value={form.deviceType} onChange={change("deviceType")} options={TYPES}/><Input label="Department" value={form.department} onChange={change("department")}/><Input label="Building" value={form.building} onChange={change("building")}/><Input label="Floor" value={form.floor} onChange={change("floor")}/><Input label="Room" value={form.room} onChange={change("room")}/></div><Textarea label="Description" value={form.description} onChange={change("description")}/><div className="network-detail-actions"><Button variant="ghost" type="button" onClick={()=>setShowForm(false)}>Cancel</Button><Button type="submit" loading={formBusy}>Save device</Button></div></form></Modal>}<ConfirmationDialog open={Boolean(confirm)} onClose={()=>setConfirm(null)} onConfirm={remove} danger title="Delete network device" message={confirm?`Delete ${confirm.name}? This cannot be undone.`:""} confirmLabel="Delete device"/></main></Layout>;
}
