import{Card,CardBody,CardHeader,Modal}from"../../design-system";import AssetActions from"./AssetActions";import AssetDocuments from"./AssetDocuments";import AssetLifecycle from"./AssetLifecycle";import AssetSpecifications from"./AssetSpecifications";import AssetStatus from"./AssetStatus";import{assetName,ownerOf}from"./assetUtils";
const Item=({label,children})=><div><dt>{label}</dt><dd>{children||"Not recorded"}</dd></div>;
export default function AssetDetails({asset,open,onClose,enumLabel,formatDate,formatDateTime,canManage,onEdit,onCustody,onRepair,onDestroy,onPreview}){if(!asset)return null;const owner=ownerOf(asset);return <Modal open={open} onClose={onClose} title={`${asset.itemNumber||asset.assetId} · ${assetName(asset)}`} size="lg"><div className="asset-details-layout"><div className="asset-details-main"><Card><CardHeader title="Asset overview" action={<AssetStatus status={asset.status} enumLabel={enumLabel}/>}/><CardBody><dl className="asset-detail-grid"><Item label="Asset ID">{asset.itemNumber||asset.assetId}</Item><Item label="Name">{assetName(asset)}</Item><Item label="Category">{asset.deviceType==="other"?asset.customDeviceType:enumLabel("deviceType",asset.deviceType)}</Item><Item label="Serial number">{asset.serialNumber}</Item>
<Item label="Status">{enumLabel("assetStatus",asset.status||"active")}</Item>
<Item label="Asset value">{asset.assetValue!=null?Number(asset.assetValue).toLocaleString():null}</Item>
<Item label="Supplier">{asset.supplier || "Not recorded"}</Item>
<Item label="Warranty">{asset.hasWarranty 
  ? `${asset.warrantyStartDate ? formatDate(asset.warrantyStartDate) : 'N/A'} to ${asset.warrantyEndDate ? formatDate(asset.warrantyEndDate) : 'N/A'}` 
  : "No warranty"
}</Item></dl></CardBody></Card><AssetSpecifications asset={asset}/><Card><CardHeader title="Ownership and custody"/><CardBody><dl className="asset-detail-grid"><Item label="Current user">{owner.name}</Item><Item label="Employee ID">{owner.employeeId}</Item><Item label="Department">{owner.department}</Item><Item label="Assigned date">{asset.issueDate?formatDate(asset.issueDate):null}</Item><Item label="Location">{asset.location}</Item></dl></CardBody></Card><AssetLifecycle events={asset.lifecycleEvents} formatDateTime={formatDateTime}/><AssetDocuments asset={asset} onPreview={onPreview}/></div><aside><AssetActions asset={asset} canManage={canManage} onEdit={onEdit} onCustody={onCustody} onRepair={onRepair} onDestroy={onDestroy}/></aside></div></Modal>;}
