import{Card,CardBody,CardHeader,Modal}from"../../design-system";import AssetActions from"./AssetActions";import AssetDocuments from"./AssetDocuments";import AssetLifecycle from"./AssetLifecycle";import AssetSpecifications from"./AssetSpecifications";import AssetStatus from"./AssetStatus";import{assetName,ownerOf}from"./assetUtils";import{useTranslation}from"../../i18n/LanguageContext";
export default function AssetDetails({asset,open,onClose,enumLabel,formatDate,formatDateTime,canManage,onEdit,onCustody,onRepair,onDestroy,onPreview}){const{t}=useTranslation();if(!asset)return null;const owner=ownerOf(asset);const Item=({label,children})=><div><dt>{label}</dt><dd>{children||t('assetPage.notRecorded')}</dd></div>;return <Modal open={open} onClose={onClose} title={`${asset.itemNumber||asset.assetId} · ${assetName(asset)}`} size="lg"><div className="asset-details-layout"><div className="asset-details-main"><Card><CardHeader title={t('assetPage.assetOverview')} action={<AssetStatus status={asset.status} enumLabel={enumLabel}/>}/><CardBody><dl className="asset-detail-grid"><Item label={t('assetPage.assetId')}>{asset.itemNumber||asset.assetId}</Item><Item label={t('assetPage.name')}>{assetName(asset)}</Item><Item label={t('assetPage.category')}>{asset.deviceType==="other"?asset.customDeviceType:enumLabel("deviceType",asset.deviceType)}</Item><Item label={t('assetPage.serialNumber')}>{asset.serialNumber}</Item>
<Item label={t('assetPage.status')}>{enumLabel("assetStatus",asset.status||"active")}</Item>
<Item label={t('assetPage.assetValue')}>{asset.assetValue!=null?Number(asset.assetValue).toLocaleString():null}</Item>
<Item label={t('assetPage.supplier')}>{asset.supplier || t('assetPage.notRecorded')}</Item>
<Item label={t('assetPage.warranty')}>{asset.hasWarranty 
  ? `${asset.warrantyStartDate ? formatDate(asset.warrantyStartDate) : 'N/A'} to ${asset.warrantyEndDate ? formatDate(asset.warrantyEndDate) : 'N/A'}` 
  : t('assetPage.noWarranty')
}</Item></dl></CardBody></Card><AssetSpecifications asset={asset}/><Card><CardHeader title={t('assetPage.ownershipAndCustody')}/><CardBody><dl className="asset-detail-grid"><Item label={t('assetPage.currentUser')}>{owner.name}</Item><Item label={t('assetPage.employeeId')}>{owner.employeeId}</Item><Item label={t('assetPage.department')}>{owner.department}</Item><Item label={t('assetPage.assignedDate')}>{asset.issueDate?formatDate(asset.issueDate):null}</Item></dl></CardBody></Card><AssetLifecycle events={asset.lifecycleEvents} formatDateTime={formatDateTime}/><AssetDocuments asset={asset} onPreview={onPreview}/></div><aside><AssetActions asset={asset} canManage={canManage} onEdit={onEdit} onCustody={onCustody} onRepair={onRepair} onDestroy={onDestroy}/></aside></div></Modal>;}
